### ISSUE TITLE
Rename rose project

### ISSUE THREAD

**Issue by GMLudo** [saghul/aiouv#4]
Hi,

I'm preparing a commit with a setup.py, but I have an issue on PyPI: rose is already taken:
https://pypi.python.org/pypi/rose

Personally, I'm not a big fan to have a different name on PyPI and on Github, I suggest to rename rose directly to avoid problems.
Some suggestions: aiorose, aiouv, asyncio_rose, asyncio_pyuv, pyuv_rose...

What's your opinion ?

**Comment by GMLudo** [comment]
Or maybe something with `loop` word.
In fact, for me, rose isn't a remplacement of asyncio, but only for loop, is it ?

**Comment by saghul** [comment]
I like "aiouv", looks like it suits the project :-)

Once #3 lands, I'll rename the GH project to "aiouv" and give you commit access so you can rename the project internally and prepare a release :-)

Cheers!

**Comment by GMLudo** [comment]
Ok ;-)

To avoid another surprise with the name, could you reserve this name in PyPI ?
Or I can do that myself, as you like.

**Comment by saghul** [comment]
Done! https://pypi.python.org/pypi/aiouv/

**Comment by haypo** [comment]
https://pypi.python.org/pypi/aiouv contains " Home Page: http://github.com/saghul/aiodns ". The homepage is wrong, it should be https://github.com/saghul/rose

By the way, you may also rename the github project to be more consistent ;-)

**Comment by saghul** [comment]
Hey Victor, thanks for stopping by! Yeah, that is still in flux, I just
registered it in a rush :-)

**Comment by saghul** [comment]
Ok, renamed the GH project and fixed the PyPI page for now.

**Comment by haypo** [comment]
I started to get a look at the project, but there is still an issue: the Python module is still called rose... Could you also rename it to aiouv please? It would be easier if I start to send pull request, to avoid conflicts.

**Comment by haypo** [comment]
The following change finish to rename rose to aiouv:
https://github.com/saghul/aiouv/commit/47da426e33bfc2cbc32cdba3b4956790018014e9

**Comment by saghul** [comment]
Awesome!
